# Generated by Django 5.0.1 on 2024-02-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_no',
            field=models.IntegerField(default=0),
        ),
    ]
