# Generated by Django 5.0.1 on 2024-05-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_order_table_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRGen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.ImageField(blank=True, upload_to='code'),
        ),
    ]
