# Generated by Django 5.0.1 on 2024-05-11 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_qrgen_order_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='code',
        ),
    ]
