# Generated by Django 5.0.1 on 2024-05-11 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_order_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrgen',
            old_name='img',
            new_name='imag',
        ),
    ]
